### ISSUE TITLE
Almost there!! BUT Question about Required Elements

### ISSUE THREAD

**Issue by dasi0075** [dasi0075/saas-website#10]
Hi Thomas, I am almost finished!! Fixed the colour problems and have almost all green highlights from Markbot. My nav hover works and he oscillates in approving and then sometimes complain about it.
My question is that there is now only one requirement he makes for sign up page.
Is asking for this
<img width="419" alt="Screen Shot 2019-04-17 at 10 09 36 PM" src="https://user-images.githubusercontent.com/43067752/56333331-cec13000-6161-11e9-990d-1166b7b7e744.png">

But I do have it
<img width="445" alt="Screen Shot 2019-04-17 at 10 40 57 PM" src="https://user-images.githubusercontent.com/43067752/56333352-e5678700-6161-11e9-8e4b-9fe72d9f95f8.png">

So how or what could I be doing wrong in this case? 
Thank you

**Comment by dasi0075** [comment]
<img width="931" alt="Screen Shot 2019-04-17 at 11 27 50 PM" src="https://user-images.githubusercontent.com/43067752/56335279-e43a5800-6169-11e9-9077-2c71b24c7e5c.png">
<img width="931" alt="Screen Shot 2019-04-17 at 11 28 11 PM" src="https://user-images.githubusercontent.com/43067752/56335280-e43a5800-6169-11e9-8ad3-f38e6cea0f32.png">
<img width="644" alt="Screen Shot 2019-04-17 at 11 28 17 PM" src="https://user-images.githubusercontent.com/43067752/56335281-e43a5800-6169-11e9-9d3b-699c17eb979d.png">

**Comment by dasi0075** [comment]
I just can't believe I just coded my FIRST website by myself!!! Only one little thing to go through!!!
Thank you Thomas for your classes, I can tell Ive learned a ton of stuff!

**Comment by dasi0075** [comment]
Got it!!!! Cant believe I finished!! @thomasjbradley

**Comment by thomasjbradley** [comment]
Yay! Good work!
